[tool.poetry]
name = "onlypets"
version = "0.1.0"
description = ""
authors = ["Levy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.2"
gunicorn = "^20.1.0"
docker = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
