# Generated by Django 3.2.16 on 2022-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('Peso', models.CharField(blank=True, default='', max_length=300)),
                ('Nascimento', models.CharField(blank=True, default='', max_length=300)),
                ('Especie', models.CharField(max_length=300)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Sexo', max_length=300, verbose_name='Sexo')),
                ('Raça', models.CharField(max_length=300)),
                ('Pelagem', models.CharField(choices=[('CL', 'Pelo curto e liso'), ('CD', 'Pelo curto e duro'), ('LL', 'Pelo longo e liso'), ('LO', 'Pelo longo ondulado'), ('PD', 'Pelagem dupla')], default='Pelagem', max_length=300, verbose_name='Pelagem')),
                ('ImagemPet', models.ImageField(upload_to='', verbose_name='Foto do pet')),
            ],
        ),
    ]
