# Generated by Django 3.2.15 on 2022-11-10 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20221109_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_pet',
            old_name='Especie',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='cadastro_pet',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cadastro_pet',
            old_name='Raça',
            new_name='raca',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='ImagemPet',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='Nascimento',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='Pelagem',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='Peso',
        ),
        migrations.RemoveField(
            model_name='cadastro_pet',
            name='Sexo',
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='imagemPet',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto do pet'),
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='nascimento',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='pelagem',
            field=models.CharField(choices=[('-', 'Escolha a pelagem do pet'), ('PCL', 'Pelo curto e liso'), ('PCD', 'Pelo curto e duro'), ('PLL', 'Pelo longo e liso'), ('PLO', 'Pelo londo e ondulado'), ('PD', 'Pelagem dupla')], default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='peso',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='sexo',
            field=models.CharField(choices=[('-', 'Escolha o sexo do seu pet'), ('m', 'macho'), ('f', 'fêmea')], default='-', max_length=300),
        ),
        migrations.AddField(
            model_name='cadastro_pet',
            name='teste2',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
