# Generated by Django 3.2.15 on 2022-11-17 19:41

from django.db import migrations, models
import pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20221110_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pet',
            name='imagemPet',
            field=models.ImageField(blank=True, null=True, upload_to=pet.models.picture_directory_path, verbose_name='Foto do pet'),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='pelagem',
            field=models.CharField(choices=[('-', 'Escolha a pelagem do pet'), ('PCL', 'Pelo curto e liso'), ('PCD', 'Pelo curto e duro'), ('PLL', 'Pelo longo e liso'), ('PLO', 'Pelo londo e ondulado'), ('PD', 'Pelagem dupla')], default='-', max_length=300, validators=[pet.models.pelo_validator]),
        ),
        migrations.AlterField(
            model_name='cadastro_pet',
            name='sexo',
            field=models.CharField(choices=[('-', 'Escolha o sexo do seu pet'), ('m', 'Macho'), ('f', 'Fêmea')], default='-', max_length=300, validators=[pet.models.sex_validator]),
        ),
    ]
