# Generated by Django 3.2.16 on 2022-12-12 16:42

from django.db import migrations, models
import pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_cadastro_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_pet',
            name='imagemPet',
            field=models.ImageField(blank=True, default='pet_default/default_pic.png', null=True, upload_to=pet.models.picture_directory_path, verbose_name='Foto do pet'),
        ),
    ]
