# Generated by Django 3.2.15 on 2022-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('Sobrenome', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=300)),
                ('Telefone', models.CharField(max_length=300)),
                ('Senha', models.CharField(max_length=300)),
                ('Confirmar_Senha', models.CharField(max_length=300)),
            ],
        ),
    ]
