# Generated by Django 3.2.15 on 2022-10-27 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_pessoa',
            name='Confirmar_Senha',
        ),
        migrations.RemoveField(
            model_name='cadastro_pessoa',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='cadastro_pessoa',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='cadastro_pessoa',
            name='Senha',
        ),
        migrations.RemoveField(
            model_name='cadastro_pessoa',
            name='Sobrenome',
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
