# Generated by Django 3.2.16 on 2022-11-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('cadastro', '0002_auto_20221027_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='Clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='Crmv',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
