# Generated by Django 3.2.16 on 2022-11-22 18:04

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20221118_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_pessoa',
            name='imagemVet',
            field=models.ImageField(blank=True, null=True, upload_to=cadastro.models.picture_directory_path, verbose_name='Foto do Veterinário'),
        ),
    ]
