# Generated by Django 3.2.16 on 2022-12-08 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='auth.user'),
            preserve_default=False,
        ),
    ]
