# Generated by Django 3.2.16 on 2022-12-12 16:42

from django.db import migrations, models
import veterinario.models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0002_servico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nome',
        ),
        migrations.AddField(
            model_name='servico',
            name='serv',
            field=models.CharField(choices=[('-', 'Escolha um Serviço'), ('ES', 'Exame de Sangue'), ('RD', 'Radiografia'), ('VC', 'Vacinação'), ('AG', 'Avaliação Geral')], default='-', max_length=300, validators=[veterinario.models.sev_validator]),
        ),
    ]
