# Generated by Django 4.1.2 on 2022-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinario', '0003_auto_20221212_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9999),
        ),
    ]
