# Generated by Django 3.2.16 on 2022-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroCartao', models.CharField(max_length=300)),
                ('NomeCartao', models.CharField(max_length=300)),
                ('DataExpirar', models.DateField(verbose_name='Data de Expiração')),
                ('CodCVV', models.CharField(max_length=300)),
                ('Padrao', models.BooleanField(default=False, verbose_name='Usar como padrão')),
            ],
        ),
    ]
