# Generated by Django 3.2.16 on 2022-11-18 19:33

import clinicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='imagemClinica',
            field=models.ImageField(blank=True, null=True, upload_to=clinicas.models.picture_directory_path, verbose_name='Foto da clinica'),
        ),
    ]
