# Generated by Django 4.1.2 on 2022-12-08 22:09

import clinicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_clinica_imagemclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='imagemClinica',
            field=models.ImageField(blank=True, default='clinica_default/default_pic.png', null=True, upload_to=clinicas.models.picture_directory_path, verbose_name='Foto da clinica'),
        ),
    ]
